server:
  port: 8011

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true